[package]
name = "muttest-core"
version = "0.1.0-alpha"
edition = "2021"
description = "effective mutation testing for Rust"
autoexamples = false

[dependencies]
lazy_static = "1.4.0"
thiserror = "1.0.30"
serde = "1"
quote = "1"
proc-macro2 = {version = "1", features = ["span-locations"]}

[dev-dependencies]
muttest-codegen = { path = "codegen" }

[workspace]
members = [".", "codegen", "app", "examples", "api"]
