[package]
name = "muttest"
version = "0.1.0-alpha"
edition = "2021"
description = "effective mutation testing for Rust"
autoexamples = false

[dependencies]
muttest-codegen = { path = "codegen" }
lazy_static = "1.4.0"

[workspace]
members = [".", "codegen", "app", "examples"]

