[tasks.examples]
description = "Run Mutation Testing on exampes"
command = "cargo"
args = ["run", "-p", "cargo-muttest", "--", "muttest", "-p", "muttest-examples"]
workspace = false
cwd = "examples"

[tasks.selftest]
description = "Run Mutation Testing on muttest-rs itself"
command = "cargo"
args = ["run", "-p", "cargo-muttest", "--", "muttest", "-p", "muttest-selftest"]
workspace = false

[tasks.selftest-nightly]
description = "Run Mutation Testing on muttest-rs itself, nightly version"
toolchain = "nightly"
env.RUSTFLAGS = "--cfg procmacro2_semver_exempt"
command = "cargo"
args = ["run", "-p", "cargo-muttest", "--", "muttest", "-p", "muttest-selftest"]
workspace = false
