[tasks.examples]
description = "Run Mutation Testing on exampes"
command = "cargo"
args = ["run", "-p", "cargo-muttest", "--", "muttest"]
workspace = false
cwd = "examples"

[tasks.selftest]
description = "Run Mutation Testing on muttest-rs itself"
command = "cargo"
args = ["run", "-p", "cargo-muttest", "--", "muttest"]
workspace = false
