[package]
name = "cargo-muttest"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "3.1.9", features = ["derive", "cargo"] }
cargo_metadata = "0.15.0"
thiserror = "1.0.30"
csv = "1.1"
serde = "1"
muttest-core = { path = ".." }

[[bin]]
name = "cargo-muttest"
path = "main.rs"
test = false
bench = false
