[package]
name = "muttest-codegen"
version = "0.1.0-alpha"
edition = "2021"

[dependencies]
proc-macro2 = "1.0.24"
syn = "1.0.60"
quote = "1.0.9"

[lib]
proc_macro = true
doctest = false
test = false
