name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
      - name: Cache
        uses: actions/cache@v3.0.8
        with:
          path: target ~/.cargo
          key: cargo-cache
      - name: Build
        run: cargo build --workspace --verbose
      - name: Run tests
        run: cargo test --verbose

  build-nightly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - name: Cache
        uses: actions/cache@v3.0.8
        with:
          path: target ~/.cargo
          key: cargo-cache-nightly
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose

  check-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          components: rustfmt
      - name: Check format
        run: cargo fmt --check --all

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          components: clippy
      - name: Run Clippy
        run: cargo clippy --all --tests -- --deny clippy::all

  selftest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
      - name: Cache
        uses: actions/cache@v3.0.8
        with:
          path: target ~/.cargo
          key: cargo-cache
      - name: Run selftest
        run: cargo run -p cargo-muttest -- muttest -p muttest-core
        # TODO: selftest other packages?

  examples:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
      - name: Cache
        uses: actions/cache@v3.0.8
        with:
          path: target ~/.cargo
          key: cargo-cache
      - name: Run examples
        run: cargo run -p cargo-muttest -- muttest -p muttest-examples
